CREATE MULTISET TABLE sandbox.nvp_sr_merchant_onboarding ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO,
     MAP = TD_MAP1
     (
      merchant_uuid VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      country_id VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      confirmed_appt VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      no_show VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      no_show_per VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      mx_risk VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      ms_case VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      is_live VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      is_bt_active VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      no_login VARCHAR(36) CHARACTER SET LATIN NOT CASESPECIFIC,
      read_received VARCHAR(36) CHARACTER SET UNICODE CASESPECIFIC
      );


